accounts/urls.py
from django.urls import path
from . import views as accounts_view

app_name = 'accounts'

urlpatterns = [
    path('login/', accounts_view.login, name="login"),
    path('logout/', accounts_view.logout, name="logout"),
    path('signup/', accounts_view.signup, name="signup"),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path , include
from itess import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itess/', include('itess.urls')),
    path('window/', include('window.urls')),
    path('accounts/', include('accounts.urls')),
    
]

# url을 만들어주겠다.
#urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

itess/urls.py
from django.urls import path
from . import views
app_name = "itess"

urlpatterns = [
    path('informations/',views.get_infos, name = "informations"),
    
]

window/urls.py
from django.urls import path
from . import views as window_views
app_name = "window"

urlpatterns = [
    path('window/', window_views.menu, name = "menu"),
    path('window/about/', window_views.about, name = "about"),
    path('window/incheon/', window_views.incheon, name = "incheon"),
    path('window/seoul/', window_views.seoul, name = "seoul"),
    path('show/<str:topic_title>/', window_views.show, name='show'),
    #path('link/', window_views.link, name='link'),
   
    path('zzim/', window_views.zzim, name='zzim'),
    path('window/myfage', window_views.myfage, name='myfage'),
    # commnet path
    path('show/<str:topic_title>/comment/', window_views.comment , name='comment'),

    # 복붙...
    path('articles/<int:article_id>/edit/', window_views.edit, name="edit"),
    path('articles/<int:article_id>/delete/', window_views.delete, name="delete"),
    path('comments/', window_views.comments, name="comments"),
    path('comments/<int:comment_id>/edit/', window_views.edit_comment, name="edit_comment"),
    path('comments/delete/', window_views.delete_comment, name="delete_comment"),

]

window/models.py
from django.db import models

# Create your models here.

window/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from itess.models import Topic, Information
from accounts.models import Article, Comment, ArticleImages, Board, HashTag
from django.contrib.auth.models import User
import requests , re, json
# Create your views here.

java = Topic.objects.filter(name = '자바')
cloud = Topic.objects.filter(name = '클라우드')
Big_Data = Topic.objects.filter(name = '빅데이터')
IOT = Topic.objects.filter(name = 'IOT')
AI = Topic.objects.filter(name = 'AI')
python = Topic.objects.filter(name = '파이썬')
VR = Topic.objects.filter(name = 'VR')
C = Topic.objects.filter(name = 'C언어')
all_data = Topic.objects.all()

context = {
        'java' : java,
        'cloud' : cloud,
        'Big_Data' : Big_Data,
        'Iot' : IOT,
        'Ai' : AI,
        'python' : python,
        'Vr' : VR,
        'C' : C,
        'all_data' : all_data,
        'title' : {
            '자바': '',
            '클라우드': '',
            '빅데이터':'',
            'IOT':'',
            'AI':'',
            '파이썬':'',
            'VR':'', 
            'C언어':'',
        },
        
    }

def menu(request):
    return render(request, 'window/index.html', context)

def about(request):
    return render(request, 'window/about.html', context)    

def incheon(request):
    return render(request, 'window/incheon.html', context)    

def seoul(request):
    return render(request, 'window/seoul.html', context)    

def zzim(request):
    id =request.user.id
    info_id = request.POST['info']
    info = Information.objects.get(id=info_id)
    info.zzim_user.add(id)
    return HttpResponse('', status=200)   

def myfage(request):
    user = request.user
    l = request.user.zzim_info.all()
    
    print(l)
    context2={
        'myfages':l,
       
    }
    return render(request, 'window/zzim.html', context2)

def show(request, topic_title):        
    if( topic_title == "자바" ):
        return render(request, 'window/java.html', context)
    if( topic_title == "클라우드" ):
        return render(request, 'window/cloud.html', context)
    if( topic_title == "빅데이터" ):
        return render(request, 'window/bigdata.html', context)
    if( topic_title == "파이썬" ):
        return render(request, 'window/python.html', context)
    if( topic_title == "Iot" ):
        return render(request, 'window/IOT.html', context)
    if( topic_title == "Ai" ):
        return render(request, 'window/AI.html', context)
    if( topic_title == "C언어" ):
        return render(request, 'window/c.html', context)
    if( topic_title == "Vr" ):
        return render(request, 'window/vr.html', context)

# 여기다가 댓글 달기 구현
def comment(request, topic_title):
    return render(request, 'window/index.html', context) 


# 복붙...

def edit(request, article_id):
    article = Article.objects.get(id=article_id)
    if article.is_permitted(request.user.id):
        if request.method == "POST":
            article.contents = request.POST["contents"]
            article.save()
            return redirect('articles')
        else:
            context = {
                'article': article
            }
            return render(request, 'article/edit.html', context)
    else:
        return redirect('articles')

def delete(request, article_id):
    article = Article.objects.get(id=article_id)
    if article.is_permitted(request.user.id):
        article.delete()
        return redirect('articles')
    else:
        return redirect('articles')

def comments(request):
    if request.method == "POST":
        if request.user.is_authenticated :
            contents = request.POST["contents"]
            article_id = request.POST["article_id"]
        
            if request.POST["form_method"] == "create":
                comment = Comment()
                # 첫번째 comment.user_id = request.user.id
            elif request.POST["form_method"] == "edit":
                comment_id = request.POST["comment_id"]
                comment = Comment.objects.get(id=comment_id)
                if comment.user_id != request.user.id:
                    return HttpResponse('', status=401)   
            comment.contents = contents
            comment.article_id = article_id
            comment.user_id = request.user.id
            comment.save()
            context = {
                'method': request.POST["form_method"],
                'comment': comment.contents,
                'username': comment.user.username,
                'comment_id': comment.id,
                'article_id': comment.article_id,
            }
            return HttpResponse(json.dumps(context), content_type='application/json')
        else:
            context = {
                'status': 401,
                'message': '로그인이 필요합니다.'
            }
            return HttpResponse(json.dumps(context), status=401, content_type="application/json")

def delete_comment(request):
    if request.method == "POST":
        comment_id = request.POST["comment_id"]
        comment = Comment.objects.get(id=comment_id)
        if comment.user_id == request.user.id:
            comment.delete()
            return HttpResponse('', status=204)
        else :
            return HttpResponse('' , status=401)

def edit_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.method == "POST":
        comment.contents = request.POST["contents"]
        comment.save()
        return redirect('articles')
    else:
        context = {
            'comment': comment
        }
        return render(request, 'comment/edit.html', context)

# 복붙...



#def link(request):
#    if request.method == "POST":
#        data = request.POST["link_address"]
#        print(data)
#        return HttpResponse(data)
          
    #print(request)
    #if request.method == "POST":
    #    data = request.POST["link_address"]
        # print(data.split('?'))
        # return HttpResponse(data.split('?')[1])
     

window/templates/window/about.html
about.html

window/templates/window/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="#">(주)집에가고 싶다</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/articles">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

window/templates/window/index.html
<!DOCTYPE html>
<html lang="zxx">
{% load static %}

<head>
<style>
  .navigation{
    background-color: gray;
  }
</style>
  <meta charset="utf-8">
  <title>Educenter</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css'%}">
  <!-- animation css -->
  <link rel="stylesheet" href="{% static 'plugins/animate/animate.css'%}">
  <!-- aos -->
  <!-- venobox popup -->
  <link rel="stylesheet" href="{% static 'plugins/venobox/venobox.css'%}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css'%}">

  {% comment %} <!--Favicon-->
  <link rel="shortcut icon" href="{%"images/favicon.ico" type="image/x-icon"%}">
  <link rel="icon" href="{%"images/favicon.ico" type="image/x-icon"%}"> {% endcomment %}

</head>

<body>
  <a href="{% static 'plugins/bootstrap/bootstrap.min.css' %}"></a>
  

  <!-- header -->
  <header class="fixed-top header">
    <!-- navbar -->
    <div class="navigation w-100" >
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light p-0">
          <a class="navbar-brand" href="{% url 'window:menu'%}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
          <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ml-auto text-center">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'window:menu'%}">Home</a>
              </li>
              <li class="nav-item @@about">
                <a class="nav-link" href="{% url 'window:about'%}">About</a>
              </li>
              <li class="nav-item @@courses">
                <a class="nav-link" href="https://google.com">COURSES</a>
              </li>
              <li class="nav-item @@events">
                <a class="nav-link" href="events.html">EVENTS</a>
              </li>
              <li class="nav-item @@blog">
                <a class="nav-link" href="{% url 'window:myfage'%}">myfage</a>
              </li>
              <li class="nav-item dropdown view">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  지역별
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'window:incheon' %}">인천</a>
                  <a class="dropdown-item" href="{% url 'window:seoul' %}">서울</a>
                  <a class="dropdown-item" href="notice.html">부산</a>
                  <a class="dropdown-item" href="notice-single.html">Notice Details</a>
                  <a class="dropdown-item" href="research.html">Research</a>
                  <a class="dropdown-item" href="scholarship.html">Scholarship</a>
                  <a class="dropdown-item" href="course-single.html">Course Details</a>
                  <a class="dropdown-item" href="event-single.html">Event Details</a>
                  <a class="dropdown-item" href="blog-single.html">Blog Details</a>
                 
                </div>
              </li>
              <li class="nav-item @@contact">
                <a class="nav-link" href="contact.html">CONTACT</a>              
              </li>
                <li>
                   {% if user.is_authenticated %}
                    <a class="btn btn-outline-primary" href="{% url 'accounts:logout' %}">{{user.username}}</a>
                    {% else %}
                    <a class="btn btn-outline-dark" href="{% url 'accounts:login' %}">로그인 </a>
                    <a class="btn btn-outline-dark" href="{% url 'accounts:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <!-- /header -->
  <!-- Modal -->
  <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content rounded-0 border-0 p-4">
        <div class="modal-header border-0">
          <h3>Register !!!!!!!!!!!!!!</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="login">
            <form action="#" class="row">
              <div class="col-12">
                <input type="text" class="form-control mb-3" id="signupPhone" name="signupPhone" placeholder="Phone">
              </div>
              <div class="col-12">
                <input type="text" class="form-control mb-3" id="signupName" name="signupName" placeholder="Name">
              </div>
              <div class="col-12">
                <input type="email" class="form-control mb-3" id="signupEmail" name="signupEmail" placeholder="Email">
              </div>
              <div class="col-12">
                <input type="password" class="form-control mb-3" id="signupPassword" name="signupPassword"
                  placeholder="Password">
              </div>
              <div class="col-12">
                <button type="submit" class="btn btn-primary">SIGN UP</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content rounded-0 border-0 p-4">
        <div class="modal-header border-0">
          <h3>Login</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="#" class="row">
            <div class="col-12">
              <input type="text" class="form-control mb-3" id="loginPhone" name="loginPhone" placeholder="Phone">
            </div>
            <div class="col-12">
              <input type="text" class="form-control mb-3" id="loginName" name="loginName" placeholder="Name">
            </div>
            <div class="col-12">
              <input type="password" class="form-control mb-3" id="loginPassword" name="loginPassword"
                placeholder="Password">
            </div>
            <div class="col-12">
              <button type="submit" class="btn btn-primary">LOGIN</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <br>
  <br>
  <br>
  <br>
  <br>
  <!-- courses -->
  <section class="section-sm">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="d-flex align-items-center section-title justify-content-between">
            <h2 class="mb-0 text-nowrap mr-3">수강 목록</h2><br><br><br>
            <div class="border-top w-100 border-primary d-none d-sm-block"></div>
            <div>
              <a href="courses.html" class="btn btn-sm btn-primary-outline ml-sm-3 d-none d-sm-block"></a>
            </div>
          </div>
        </div>
      </div>
      <!-- course list -->
      <div class="row justify-content-center">
        <!-- course item -->
        
        {% for topic in title %}
        <div class="col-lg-4 col-sm-6 mb-5 item">
          <div class="card p-0 border-primary rounded-0 hover-shadow">
            {% if topic.title == '자바' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/java.jpg' %}" width="300" height="300" alt="course thumb">
            {% elif topic.title == '클라우드' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/cloud.jpg' %}" width="300" height="300" alt="course thumb">       
            {% elif topic.title == '빅데이터' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/big.jpg' %}" width="300" height="300" alt="course thumb">
            {% elif topic.title == 'Iot' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/IOT.jpg' %}" width="300" height="300" alt="course thumb">
            {% elif topic.title == 'Ai' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/AI.jpg' %}" width="300" height="300" alt="course thumb">
            {% elif topic.title == 'Vr' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/VR.jpg' %}" width="300" height="300" alt="course thumb">
            {% elif topic.title == 'C언어' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/C.jpg' %}" width="300" height="300" alt="course thumb">
            {% elif topic.title == '파이썬' %}
              <img class="card-img-top rounded-0" src= "{% static 'images/courses/python.jpg' %}"  width="300" height="300" alt="course thumb">
            {% endif %}
            <div class="card-body">
              <ul class="list-inline mb-2">
                <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i></li>
                <li class="list-inline-item">{{ topic.title }}</i></li>
              </ul>
              <a href="{% url 'window:show' topic.title %}">
                <button class="btn btn-primary btn-sm gogo" data-title="{{ topic.title }}">바로 가기</button>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
          
      <!-- /course list -->
      <!-- mobile see all button -->
      <div class="row">
        <div class="col-12 text-center">
          <a href="courses.html" class="btn btn-sm btn-primary-outline d-sm-none d-inline-block">sell all</a>
        </div>
      </div>
    </div>
  </section>
  <!-- /courses -->

  <!-- footer -->
  <footer>
    <!-- copyright -->
    <div class="copyright py-4 bg-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-7 text-sm-left text-center">
            <p class="mb-0">Copyright
              <script>
                var CurrentYear = new Date().getFullYear()
                document.write(CurrentYear)
              </script>
              © Theme By <a href="#"></a></p> . All Rights Reserved.
          </div>
          <div class="col-sm-5 text-sm-right text-center">
            <ul class="list-inline">
              <li class="list-inline-item"><a class="d-inline-block p-2" href="https://www.facebook.com/themefisher"><i
                    class="ti-facebook text-primary"></i></a></li>
              <li class="list-inline-item"><a class="d-inline-block p-2" href="https://www.twitter.com/themefisher"><i
                    class="ti-twitter-alt text-primary"></i></a></li>
              <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i
                    class="ti-instagram text-primary"></i></a></li>
              <li class="list-inline-item"><a class="d-inline-block p-2" href="https://dribbble.com/themefisher"><i
                    class="ti-dribbble text-primary"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- /footer -->
  
  <!-- jQuery -->
  <script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
  <!-- Bootstrap JS -->
  <script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
  <!-- slick slider -->
  <script src="{% static 'plugins/slick/slick.min.js' %}"></script>
  <!-- aos -->
  <script src="{% static 'plugins/aos/aos.js' %}"></script>
  <!-- venobox popup -->
  <script src="{% static 'plugins/venobox/venobox.min.js' %}"></script>
  <!-- mixitup filter -->
  <script src="{% static 'plugins/mixitup/mixitup.min.js' %}"></script>
  <!-- google map -->
  
  <!-- Main Script -->
  <script src="{% static 'js/script.js' %}"></script>

  <!--Function 구현 -->
  <script>
 
  </script>

</body>
</html>